name: Deploy

on:
    push:
        branches:
            - "main"

jobs:
    deploy-frontend:
        runs-on: ubuntu-latest
        name: "Deploy frontend"
        steps:
            - name: Checkout repository
              uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

            - name: Setup Bun
              uses: oven-sh/setup-bun@ecf28ddc73e819eb6fa29df6b34ef8921c743461

            - name: Run build
              run: bun install && cd web && bun run build
              env:
                  WEB_HOST: ${{ secrets.WEB_HOST }}
                  WEB_DEFAULT_API: ${{ secrets.WEB_DEFAULT_API }}

            - name: Deploy to bunny.net
              uses: ayeressian/bunnycdn-storage-deploy@922e816641b3aab7c5b4039abfd416ff3ae970c4
              with:
                source: "./web/build"
                destination: "."
                storageZoneName: "${{ secrets.BUNNY_STORAGE_ZONE_NAME }}"
                storagePassword: "${{ secrets.BUNNY_STORAGE_ZONE_PASSWORD }}"
                accessKey: "${{ secrets.BUNNY_API_KEY }}"
                pullZoneId: "${{ secrets.BUNNY_PULL_ZONE_ID }}"
                upload: "true"
                remove: "true"
                purgePullZone: "true"
                purgePullZoneDelay: "5"

    build-and-upload-backend-container-image:
        runs-on: ubuntu-latest
        name: "Build and upload backend container image"
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@c8ad1c5d0f6f39c2bc446b807fa8ea2afadcddb6

            - name: Log into registry
              uses: docker/login-action@9fe7774c8f8ebfade96f0a62aa10f3882309d517
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata
              id: meta
              uses: docker/metadata-action@b13d25e5fcf2e04305d8aedc9a6c28ebe258e934
              with:
                  images: ghcr.io/${{ github.repository_owner }}/cobalt-api
                  tags: |
                      type=raw,value=latest
                      type=sha,format=short,prefix=

            - name: Build and push container image
              uses: docker/build-push-action@dbac3ca1e5410ec04d2cce48cfbcfa3175fb8f4f
              with:
                  context: .
                  file: ./api/Dockerfile
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
