name: Deploy to bunny.net

on:
    push:
        branches:
            - "main"

jobs:
    publish:
        runs-on: ubuntu-latest
        name: "Deploy to bunny.net"
        steps:
            - name: Checkout repository
              uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

            - name: Setup Bun
              uses: oven-sh/setup-bun@ecf28ddc73e819eb6fa29df6b34ef8921c743461

            - name: Run build
              run: bun install && cd web && bun run build
              env:
                  WEB_HOST: ${{ secrets.WEB_HOST }}
                  WEB_DEFAULT_API: ${{ secrets.WEB_DEFAULT_API }}

            - name: Deploy to bunny.net
              uses: ayeressian/bunnycdn-storage-deploy@922e816641b3aab7c5b4039abfd416ff3ae970c4
              with:
                source: "./web/build"
                destination: "."
                storageZoneName: "${{ secrets.BUNNY_STORAGE_ZONE_NAME }}"
                storagePassword: "${{ secrets.BUNNY_STORAGE_ZONE_PASSWORD }}"
                accessKey: "${{ secrets.BUNNY_API_KEY }}"
                pullZoneId: "${{ secrets.BUNNY_PULL_ZONE_ID }}"
                upload: "true"
                remove: "true"
                purgePullZone: "true"
                purgePullZoneDelay: "5"
