name: Deploy to bunny.net

on:
    push:
        branches:
            - "main"

jobs:
    publish:
        runs-on: ubuntu-latest
        name: "Deploy to bunny.net"
        steps:
            - name: Checkout repository
              uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

            - name: Setup Bun
              uses: oven-sh/setup-bun@ecf28ddc73e819eb6fa29df6b34ef8921c743461

            - name: Run build
              run: bun install && bun run web:build
              env: # Or as an environment variable
                  WEB_HOST: ${{ secrets.WEB_HOST }}
                  WEB_DEFAULT_API: ${{ secrets.WEB_DEFAULT_API }}

            - name: Clean up
              run: rm -rf ./.git* node_modules package.json bun.lock

            - name: Deploy to BunnyCDN
              uses: ayeressian/bunnycdn-storage-deploy@251c77f4b9e7e683ad00086de2bef5770c3386b2
              with:
                source: "./web/dist"
                destination: "."
                storageZoneName: "${{ secrets.BUNNY_STORAGE_ZONE_NAME }}"
                storagePassword: "${{ secrets.BUNNY_STORAGE_ZONE_PASSWORD }}"
                accessKey: "${{ secrets.BUNNY_API_KEY }}"
                pullZoneId: "${{ secrets.BUNNY_PULL_ZONE_ID }}"
                upload: "true"
                remove: "true"
                purgePullZone: "true"
                purgePullZoneDelay: "5"
